### ISSUE TITLE
i can't run example, help me please

### ISSUE THREAD

**Issue by niludakup33org** [Karasiq/scalajs-highcharts#7]
`
> scalajs-highcharts-test-frontend/run
[info] Updating {file:/home/333/Downloads/scalajs-highcharts-master/}scalajs-highcharts-test-frontend...
[info] Resolving org.scala-lang#scala-library;2.12.1 ...
[info] Resolving com.github.karasiq#scalajs-highcharts_sjs0.6_2.12;1.2.0 ...
[info] Resolving org.scala-js#scalajs-library_2.12;0.6.14 ...
[info] Resolving be.doeraene#scalajs-jquery_sjs0.6_2.12;0.9.1 ...
[info] Resolving org.scala-js#scalajs-dom_sjs0.6_2.12;0.9.1 ...
[info] Resolving com.lihaoyi#scalatags_sjs0.6_2.12;0.6.2 ...
[info] Resolving com.lihaoyi#sourcecode_sjs0.6_2.12;0.1.3 ...
[info] Resolving org.scala-js#scalajs-test-interface_2.12;0.6.14 ...
[info] Resolving org.scala-js#scalajs-compiler_2.12.1;0.6.14 ...
[info] Resolving org.scala-lang#scala-compiler;2.12.1 ...
[info] Resolving org.scala-lang#scala-reflect;2.12.1 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.12;1.0.6 ...
[info] Resolving jline#jline;2.14.1 ...
[info] Resolving org.eclipse.jetty#jetty-websocket;8.1.16.v20140903 ...
[info] Resolving org.eclipse.jetty#jetty-util;8.1.16.v20140903 ...
[info] Resolving org.eclipse.jetty#jetty-io;8.1.16.v20140903 ...
[info] Resolving org.eclipse.jetty#jetty-http;8.1.16.v20140903 ...
[info] Resolving org.eclipse.jetty#jetty-server;8.1.16.v20140903 ...
[info] Resolving org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016 ...
[info] Resolving org.eclipse.jetty#jettycontinuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Compiling 6 Scala sources to /home/333/Downloads/scalajs-highcharts-master/test/frontend/target/scala-2.12/classes...
[info] Fast optimizing /home/333/Downloads/scalajs-highcharts-master/test/frontend/target/scala-2.12/scalajs-highcharts-test-frontend-fastopt.js
[info] Running com.highcharts.test.frontend.HighchartsTestApp
[error] /home/333/Downloads/scalajs-highcharts-master/test/frontend/target/scala-2.12/scalajs-highcharts-test-frontend-fastopt.js:9019
[error]   (0, $m_Lorg_scalajs_jquery_package$().jQuery$1)((function($this) {
[error]                                                  ^
[error] 
[error] TypeError: (0 , $m_Lorg_scalajs_jquery_package$(...).jQuery$1) is not a function
[error]     at $c_Lcom_highcharts_test_frontend_HighchartsTestApp$.main__V (/home/333/Downloads/scalajs-highcharts-master/test/frontend/target/scala-2.12/scalajs-highcharts-test-frontend-fastopt.js:9019:50)
[error]     at $c_Lcom_highcharts_test_frontend_HighchartsTestApp$.$$js$exported$meth$main__O (/home/333/Downloads/scalajs-highcharts-master/test/frontend/target/scala-2.12/scalajs-highcharts-test-frontend-fastopt.js:9079:8)
[error]     at $c_Lcom_highcharts_test_frontend_HighchartsTestApp$.main (/home/333/Downloads/scalajs-highcharts-master/test/frontend/target/scala-2.12/scalajs-highcharts-test-frontend-fastopt.js:9082:15)
[error]     at Object.<anonymous> (/home/333/Downloads/scalajs-highcharts-master/test/frontend/target/scala-2.12/scalajs-highcharts-test-frontend-launcher.js:2:120)
[error]     at Module._compile (module.js:570:32)
[error]     at Object.Module._extensions..js (module.js:579:10)
[error]     at Module.load (module.js:487:32)
[error]     at tryModuleLoad (module.js:446:12)
[error]     at Function.Module._load (module.js:438:3)
[error]     at Module.require (module.js:497:17)
org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:107)
	at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:156)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:684)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$60$$anonfun$apply$43$$anonfun$apply$44.apply(ScalaJSPluginInternal.scala:771)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$60$$anonfun$apply$43$$anonfun$apply$44.apply(ScalaJSPluginInternal.scala:765)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run 'last scalajs-highcharts-test-frontend/compile:run' for the full output.
[error] (scalajs-highcharts-test-frontend/compile:run) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
[error] Total time: 41 s, completed 17.08.2017 16:04:10

`

**Comment by niludakup33org** [comment]
,
   jQuery("#container").highcharts(
      new HighchartsConfig {
        override val chart: Cfg[Chart] = Chart(`type` = "bar")
        override val title: Cfg[Title] = Title(text = "Demo bar chart")
        override val xAxis: CfgArray[XAxis] = js.Array(XAxis(categories = js.Array("Apples", "Bananas", "Oranges")))
        override val yAxis: CfgArray[YAxis] = js.Array(YAxis(title = YAxisTitle(text = "Fruit eaten")))
        override val series: SeriesCfg = js.Array[AnySeries](
          SeriesBar(name = "Jane", data = js.Array[Double](1, 0, 4)),
          SeriesBar(name = "John", data = js.Array[Double](5, 7, 3))
        )
      }
    )
![screenshot from 2017-08-17 16-47-30](https://user-images.githubusercontent.com/31101364/29415455-ceba8686-836b-11e7-9e10-803a2b17c02f.png)
,

**Comment by niludakup33org** [comment]
how it's work?

**Comment by niludakup33org** [comment]
need dependency 5.0.7
